### ISSUE TITLE
Parsing APK with AppCompat

### ISSUE THREAD

**Issue by devunwired** [devunwired/apktools#12]
There is currently an issue parsing an APK that includes the AppCompat support library.

Create an empty APK that includes the bare minimum appcompat support library and an empty `AppCompatActivity`. When initializing `ApkResources`, an unexpected string offset is encountered while parsing the string pool chunk and the script throws an exception.

**Comment by idstein** [comment]
This could be related to my pull request. I think libraries use some sort of a reference or dynamic table like resource table entry type. So interpreting its data value which is a reference will result with an invalid lookup id from the string pool.

**Comment by devunwired** [comment]
Possible, though unlikely. In this particular case, the parser fails to make it through the main string pool (something it does before attempting to read type chunks). There is something about the assumptions I originally made on string pool chunks that is no longer valid.

**Comment by devunwired** [comment]
I can't say exactly which, but one of the changes in 0.7.0 has fixed this issue. Probably the restructure of the parser that @idstein proposed.

**Comment by devunwired** [comment]
Re-opening per discoveries made on Issue #15.
